logging:
  level: INFO

kafkaConsumer:
  bootstrapServer: kafka-service:19092
  topic: messages
  groupId: processing-service
  keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
  valueDeserializer: de.benkan.processing.stream.serialization.MessageDeserializer
  pollTimeoutMs: 100
