logging:
  level: INFO

kafkaProducer:
  bootstrapServer: kafka-service:19092
  topic: messages
  keySerializer: org.apache.kafka.common.serialization.StringSerializer
  valueSerializer: de.benkan.frontend.stream.serialization.MessageSerializer
  acks: all
  retries: 0
  lingerMs: 1

settingsClientConfig:
  hostName: http://settings-service
  port: 8911
  basePath: /api/v1