apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    infra: kafka
spec:
  type: LoadBalancer
  ports:
    - port: 9092
      name: kafka-internal-port
      protocol: TCP
    - port: 19092
      name: kafka-public-port
      protocol: TCP
  selector:
    infra: kafka
